  
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    target_branch: "staging"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
    default_reviewers:
      - "AMoreaux"
